baseURL = "https://alexander-jackson.github.io/"
languageCode = "en-gb"
title = "Alexander Jackson"
theme = "noteworthy"

[params]
email = "alexanderjackson@protonmail.com"
github = "alexander-jackson"

[menu]
	[[menu.main]]
		identifier = "about"
		name = "About Me"
		url = "/about"
		weight = -110
